--- #YAML:1.0
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
name: Math-RandomOrg
version: 0.05_02
abstract: Retrieve random numbers and data from the random.org webservice.
author:
  - Gregory Todd Williams <gwilliams@cpan.org>
build_requires:
  Test::More: 0.61
distribution_type: module
generated_by: Module::Install version 0.630
license: perl
no_index:
  directory:
    - inc
    - t
requires:
  LWP: 0
  Math::BigInt: 1.15
